"""Initial migration

Revision ID: 1b176d43ce09
Revises: 
Create Date: 2026-03-26 14:37:45.850449
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b176d43ce09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('FILE_UPLOAD', 'YOUTUBE_URL', 'VIMEO_URL', 'WEB_URL', name='sourcetype'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INGESTING', 'INGESTED', 'SEPARATING', 'SEPARATED', 'TRANSCRIBING', 'TRANSCRIBED', 'MAPPING', 'COMPLETED', 'FAILED', name='projectstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notation_type', sa.Enum('WESTERN', 'SARGAM', 'BOTH', name='notationtype'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('raw_audio_path', sa.Text(), nullable=True),
    sa.Column('score_xml_path', sa.Text(), nullable=True),
    sa.Column('score_midi_path', sa.Text(), nullable=True),
    sa.Column('score_pdf_path', sa.Text(), nullable=True),
    sa.Column('detected_tempo', sa.Integer(), nullable=True),
    sa.Column('detected_key', sa.String(length=50), nullable=True),
    sa.Column('detected_time_signature', sa.String(length=20), nullable=True),
    sa.Column('detected_raga', sa.String(length=100), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('stems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('instrument_type', sa.Enum('VOCALS', 'DRUMS', 'BASS', 'PIANO', 'GUITAR', 'OTHER', name='instrumenttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SEPARATING', 'SEPARATED', 'TRANSCRIBING', 'TRANSCRIBED', 'COMPLETED', 'FAILED', name='stemstatus'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('midi_path', sa.Text(), nullable=True),
    sa.Column('musicxml_path', sa.Text(), nullable=True),
    sa.Column('waveform_data_path', sa.Text(), nullable=True),
    sa.Column('sargam_json_path', sa.Text(), nullable=True),
    sa.Column('tabla_bol_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stems_project_id'), 'stems', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stems_project_id'), table_name='stems')
    op.drop_table('stems')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
